package com.android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SONGS_LIST".
 */
public class SongsList {

    private String songName;
    private String thumImage;
    private String url;

    public SongsList() {
    }

    public SongsList(String songName, String thumImage, String url) {
        this.songName = songName;
        this.thumImage = thumImage;
        this.url = url;
    }

    public String getSongName() {
        return songName;
    }

    public void setSongName(String songName) {
        this.songName = songName;
    }

    public String getThumImage() {
        return thumImage;
    }

    public void setThumImage(String thumImage) {
        this.thumImage = thumImage;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
